require('dotenv').config()

const PORT = process.env.PORT

const MONGODB_URI = process.env.NODE_ENV === 'test'
  ? process.env.TEST_MONGODB_URI
  : process.env.MONGODB_URI

const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME || 'duotqd1pb'
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET

const SIGHTENGINE_API_SECRET = process.env.SIGHTENGINE_API_SECRET
const SIGHTENGINE_API_USER = process.env.SIGHTENGINE_API_USER
const SIGHTENGINE_API_MODELS = process.env.SIGHTENGINE_API_MODELS

module.exports = {
  MONGODB_URI,
  PORT,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  SIGHTENGINE_API_SECRET,
  SIGHTENGINE_API_USER,
  SIGHTENGINE_API_MODELS
}